# Generated by Django 3.2.7 on 2021-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
