# Generated by Django 3.2.7 on 2021-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20210926_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.FloatField(),
        ),
    ]
